-- Recently played tracks (raw JSON)
CREATE TABLE SPOTIFY_ANALYTICS.RAW_DATA.RECENTLY_PLAYED (
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_DATA VARIANT
);

-- Top tracks/artists (raw JSON)
CREATE TABLE SPOTIFY_ANALYTICS.RAW_DATA.TOP_ITEMS (
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ITEM_TYPE STRING, -- 'tracks' or 'artists'
    TIME_RANGE STRING, -- 'short_term', 'medium_term', 'long_term'
    RAW_DATA VARIANT
);

-- Audio features (raw JSON)
CREATE TABLE SPOTIFY_ANALYTICS.RAW_DATA.AUDIO_FEATURES (
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_DATA VARIANT
);