-- Cleaned tracks table
CREATE TABLE SPOTIFY_ANALYTICS.TRANSFORMED.TRACKS (
    TRACK_ID STRING PRIMARY KEY,
    TRACK_NAME STRING,
    ARTIST_ID STRING,
    ARTIST_NAME STRING,
    ALBUM_ID STRING,
    ALBUM_NAME STRING,
    DURATION_MS INTEGER,
    POPULARITY INTEGER,
    EXPLICIT BOOLEAN,
    RELEASE_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Audio features table
CREATE TABLE SPOTIFY_ANALYTICS.TRANSFORMED.AUDIO_FEATURES (
    TRACK_ID STRING PRIMARY KEY,
    DANCEABILITY FLOAT,
    ENERGY FLOAT,
    KEY INTEGER,
    LOUDNESS FLOAT,
    MODE INTEGER,
    SPEECHINESS FLOAT,
    ACOUSTICNESS FLOAT,
    INSTRUMENTALNESS FLOAT,
    LIVENESS FLOAT,
    VALENCE FLOAT,
    TEMPO FLOAT,
    TIME_SIGNATURE INTEGER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Listening history
CREATE TABLE SPOTIFY_ANALYTICS.TRANSFORMED.LISTENING_HISTORY (
    PLAYED_AT TIMESTAMP_NTZ,
    TRACK_ID STRING,
    CONTEXT_TYPE STRING, -- playlist, album, etc.
    CONTEXT_URI STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);